changelog:
  exclude:
    labels:
      - skip-changelog
      - duplicate
      - invalid
      - question
  categories:
    - title: New Features
      labels:
        - feature
        - enhancement
    - title: Fixes
      labels:
        - fix
        - bug
    - title: Maintenance
      labels:
        - chore
        - dependencies
        - documentation
    - title: Other Changes
      labels:
        - "*"
